name: Call API every two minutes 1

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # 每5分钟运行一次

jobs:
  call-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call API
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.REPLICATE_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "version": "7924ac1e5d2ac99ef07f86add5c6db4c7e860ec43a030bf9507684aec112762c",
              "input": {
                "ping_flag": true
              }
            }' \
            ${{ secrets.REPLICATE_URL }}
